#use VI editor
CFLAGS=-Wall -g -DNDEBUG

all: logfind
	./logfind God worthy beginning Paul
	./logfind -o God worthy beginning Paul
	./logfind beginning WORD
	./logfind || true
	./logfind 

clean:
	rm -f logfind